### ISSUE TITLE
latest universalregistrar/uni-registrar-web not working

### ISSUE THREAD

**Issue by fqutishat** [decentralized-identity/universal-registrar#16]
```
	<h3>Caused by:</h3><pre>java.lang.ClassNotFoundException: foundation.identity.did.DIDDocument
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:555)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by fqutishat** [comment]
@peacekeeper

**Comment by peacekeeper** [comment]
@fqutishat we had to make some breaking changes in the [did-common-java](https://github.com/decentralized-identity/did-common-java) library to better align with JSON-LD and the latest developments in the DID Core spec (e.g. publicKey has been renamed to verificationMethod). If you first rebuild did-common-java and then universal-registrar, I think it should work?

@BernhardFuchs is now creating release versions of various components to reduce the use of SNAPSHOT dependencies to avoid such problems in the future.

Sorry that this is causing troubles for you.. Let us know (here or in the DIF Slack) if you still have problems or other questions...

**Comment by peacekeeper** [comment]
@fqutishat are you still having problems, or can we close this issue?
