### ISSUE TITLE
Error when trying to create dyne did document from https://uniregistrar.io

### ISSUE THREAD

**Issue by matteo-cristino** [decentralized-identity/universal-registrar#78]
I have clone latest version of main and build all from scratch and had no problem to have dyne endpoints working.
For example with the following request:
```sh
curl -X POST 'http://localhost:9080/1.0/create?method=dyne' -d '{"didDocument":{}}'
```
I get:
```json
{
  "jobId":null,
  "didState": {
    "state":"action",
    "action":"getVerificationMethod",
    "verificationMethodTemplate": [{
      "type":"Ed25519VerificationKey2018"
    }]
  },
  "didRegistrationMetadata": {
    "duration":74,
    "method":"dyne"
  },
  "didDocumentMetadata":{}
}
```
---
On the other hand if I try to use the web version:
```sh
curl -X POST 'https://uniregistrar.io:443/1.0/create?method=dyne' -d '{"didDocument":{}}'
```
I get:
```json
{
  "jobId":null,
  "didState": {
    "reason":"Cannot retrieve CREATE STATE for create request {\"jobId\":null,\"options\":null,\"secret\":null,\"didDocument\":{}} from http://driver-did-dyne:3000/1.0/create: driver-did-dyne: Name does not resolve",
    "state":"failed",
    "error":"internalError"
  },
  "didRegistrationMetadata":{},
  "didDocumentMetadata":{}
}
```
---
Is there something that I can do to fix this issue? I do not know how to debug it since on local machine it works without any problem.

Thank you in advance for your help! ✨

**Comment by BernhardFuchs** [comment]
There was an issue with the deployment of the driver on uniregistrar.io  
It is fixed now and the driver is responsive.  
Sorry for the inconvenience

**Comment by matteo-cristino** [comment]
Thank you for the quick fix! 💎

**Comment by matteo-cristino** [comment]
sorry to bother you again, but I'm having another issue on uniregistrar.io that I can not reproduce locally, now the error returned when trying to create a did document is:
```json
{
  "reason": "Cannot retrieve CREATE STATE for create request {\"jobId\":null,\"options\":{\"clientSecretMode\":true},\"secret\":{},\"didDocument\":{\"@context\":[\"https://www.w3.org/ns/did/v1\",\"https://w3id.org/security/suites/ed25519-2018/v1\",\"https://w3id.org/security/suites/secp256k1-2019/v1\",\"https://w3id.org/security/suites/secp256k1-2020/v1\",\"https://dyne.github.io/W3C-DID/specs/ReflowBLS12381.json\",{\"description\":\"https://schema.org/description\"}],\"description\":\"uniregistrar_user_test\",\"id\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"verificationMethod\":[{\"controller\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"id\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ#ecdh_public_key\",\"publicKeyBase58\":\"RxVmnvuvw8T8jR9rhxRDkiMT6he5aUfJWxABEQm1QcngYUNFwUNuGcxh51rWSTWpddiXM4rZMFE9NGsPe77FAnXG\",\"type\":\"EcdsaSecp256k1VerificationKey2019\"},{\"controller\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"id\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ#reflow_public_key\",\"publicKeyBase58\":\"9yXBgx6ea5K9GjC1goCZCzmSdccsD89KEa9HS83bFG8d1XDQchCycPf9M127Xn2Nv38MdzfCP5NhaQiHrhmesvuC7Xg57aJS2oEuXvKL12qJMiu7BnMrn2cRwYL92DDEMxvhaZ7URgRcJBmmipAADgBLD72R3bQoixpdLimFcdUmDDZsteFjREo12X8Wp4o8SAHGRnsKzgH39gupXQXejbeD7dbCUZH1K3vmPZMZq8FEfcXDvKpe3SNSZfRENwGVzizsmp\",\"type\":\"ReflowBLS12381VerificationKey\"},{\"controller\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"id\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ#bitcoin_public_key\",\"publicKeyBase58\":\"rJFQKgrz6Br2BjZQKzfRdoCeyviVTaLwjAcwaeXaDMeR\",\"type\":\"EcdsaSecp256k1VerificationKey2019\"},{\"controller\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"id\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ#eddsa_public_key\",\"publicKeyBase58\":\"DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"type\":\"Ed25519VerificationKey2018\"},{\"blockchainAccountId\":\"eip155:1:0x3b50f0381e98e51f0e837e768f24ad908145b120\",\"controller\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ\",\"id\":\"did:dyne:sandbox.uniregistrar:DfBHRpmmiE78MafEzPRYPeKn1PzBtYsbptKCro3HovMZ#ethereum_address\",\"type\":\"EcdsaSecp256k1RecoveryMethod2020\"}]}} from http://driver-did-dyne:3000/1.0/create: Connect to driver-did-dyne:3000 [driver-did-dyne/10.98.228.137] failed: Connection refused",
  "state": "failed",
  "error": "internalError"
}
``` 
Is there something I can do to fix this? Thank you verfy much for your help

**Comment by peacekeeper** [comment]
@matteo-cristino Could you share the (curl?) request you are sending that causes this?

**Comment by matteo-cristino** [comment]
The curl is the following:
```bash
curl -X 'POST' "https://uniregistrar.io/1.0/create?method=dyne" \
	 -H 'accept: application/json' \
	 -H 'Content-Type: application/json' \
	 -d '{
		"options": {
			"clientSecretMode": true
		},
		"secret": { },
		"didDocument": {
			"@context": [
				"https://www.w3.org/ns/did/v1",
				"https://w3id.org/security/suites/ed25519-2018/v1",
				"https://w3id.org/security/suites/secp256k1-2019/v1",
				"https://w3id.org/security/suites/secp256k1-2020/v1",
				"https://dyne.github.io/W3C-DID/specs/ReflowBLS12381.json",
				{
				"description": "https://schema.org/description"
				}
			],
			"description": "uniregistrar_user_test",
			"id": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
			"verificationMethod": [
				{
				"controller": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
				"id": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py#ecdh_public_key",
				"publicKeyBase58": "R8NgK399eBuLa8HU1389R1MvfVv8RacP4352E9JPpMvrzZbksnvhFjiTy3fzJGCrN2JJgPvJdmiAbJB63QSBQuVR",
				"type": "EcdsaSecp256k1VerificationKey2019"
				},
				{
				"controller": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
				"id": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py#reflow_public_key",
				"publicKeyBase58": "z9ZiSZ7bEJBAfwinVi7G5bqM7tdhobps6A6XxpuBJRYhDfsyo1F6WurxTro4UNHQWVUhMc8fPCfcDyqpsf6mSZtvRqPF2rxoJ6QpSdqBpc8gjRJcvedfEZDroaiJgtyqPhw7tbinMKAr8GbyvVaPn2npyjmKQyPMC6Kxsbx7DvabjmwjVtmP7Be1ajT2YqoinAAjcv9zcrFy4dA1FUMLZ2adJxwS73wZB9CHjkUtmEVYY45NWFuhZFiFZaWHVdHv9vpFv",
				"type": "ReflowBLS12381VerificationKey"
				},
				{
				"controller": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
				"id": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py#bitcoin_public_key",
				"publicKeyBase58": "nzj5GvFaGUdehnTr57ozKuYmjoeXwDXiJk17pAownNNi",
				"type": "EcdsaSecp256k1VerificationKey2019"
				},
				{
				"controller": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
				"id": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py#eddsa_public_key",
				"publicKeyBase58": "9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
				"type": "Ed25519VerificationKey2018"
				},
				{
				"blockchainAccountId": "eip155:1:0x9cf94517ada789d7c4e23a01637f2d7096ac0a80",
				"controller": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py",
				"id": "did:dyne:sandbox.uniregistrar:9CS9EFKotf4Evf7Dc5tyLcFZwijXzEh5XpEcFLMk83Py#ethereum_address",
				"type": "EcdsaSecp256k1RecoveryMethod2020"
				}
			]
		}
	}'
```
Thank you for the help!

**Comment by peacekeeper** [comment]
I see this in the driver logs, and then the driver seems to crash. Does this mean anything to you?

```
7:C 31 Jan 2024 22:56:17.292 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 31 Jan 2024 22:56:17.293 # Redis version=7.0.14, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 31 Jan 2024 22:56:17.293 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
7:M 31 Jan 2024 22:56:17.294 * monotonic clock: POSIX clock_gettime
7:M 31 Jan 2024 22:56:17.295 * Running mode=standalone, port=6379.
7:M 31 Jan 2024 22:56:17.295 # Server initialized
7:M 31 Jan 2024 22:56:17.296 * Ready to accept connections
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 3.71s.
🚻 Restroom started on http://0.0.0.0:3000
📁 the ZENCODE directory is: /var/contracts 

To see the OpenApi interface head your browser to: http://0.0.0.0:3000/docs
To disable OpenApi, run OPENAPI=0 yarn start

Exposing
	/api/create-1-checks.yml
	/api/create-2-sign.yml
	/api/deactivate-1-checks.yml
	/api/deactivate-2-sign.yml
	/api/update-1-checks.yml
	/api/update-2-sign.yml
node:internal/deps/undici/undici:11730
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/restroom.mjs:107:15 {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}
Node.js v18.19.0
```

**Comment by andrea-dintino** [comment]
We're looking at this now, the error is:

`  at async file:///app/restroom.mjs:107:15 { `

` cause: Error: connect ECONNREFUSED ::1:3000` 

According to the error, the aculprit is this [line](https://github.com/dyne/W3C-DID/blob/main/universal-registrar/restroom.mjs#L104-L107) which tries to call localhost:3000.   

It seems that our application is trying to reach itself at the address ::1 (ipv6 equivalent of localhost) on port 3000. The application itself is listening _partly_ on 0.0.0.0 (see: [here](https://github.com/dyne/W3C-DID/blob/main/universal-registrar/restroom.mjs#L21) ) and on localhost (which is often, **but not all OS** resolved to same address as 0.0.0.0).

We found this issue, which matches what we were guessing:
https://stackoverflow.com/questions/76844862/getting-connect-econnrefused-13000-error-while-sending-post-request-by-axio

We have 2 causes/fixes in mind:
1) for some reason, on your setup, 0.0.0.0 is not resolved to localhost (as it does on our machines), and something goes wrong and for some reason the 0.0.0.0/localhost is translated to ::1   -> we're doing a PR now, please try and see if that solves.
2) there is something else, in your system setup, that causes  0.0.0.0/localhost to be translated to ::1, if that's the case there is little we can do here.

Please let us know if the fix 1) works

**Comment by peacekeeper** [comment]
@andrea-dintino We just deployed you updated version 0.3 on https://uniregistrar.io/, and I think it works fine!

**Comment by matteo-cristino** [comment]
Now it seems to work perfectly again, thank you for all the help!

**Comment by andrea-dintino** [comment]
Yes it works! see here: https://explorer.did.dyne.org/details/did:dyne:sandbox.uniregistrar:9Y88qriCmwxB5epGrVHQRrSyTL8MmFtK9YNN34t2Lqeg
